import 'bootstrap/dist/css/bootstrap.css';
import './global.css';
import { Quicksand } from 'next/font/google';
import BootstrapClient from '@/components/BootstrapClient';

const quicksand = Quicksand({ subsets: ['latin'] });

export const metadata = {
  title: 'Supreme Reagan',
  description: 'Generated by Majesty',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  )
}
//Profile for Nigerian brewery Job Application
//https://select.alldayhr.com/job/information-communication-manager/apply

